### ISSUE TITLE
Post And Comment cards can overflow outside of columns

### ISSUE THREAD

**Issue by Cryptwo9879** [Cryptwo9879/SteemViz-2#1]
Post and comment cards have occasionally contain transactions that cause them to stretch outside normal width in columns and overlap elements in neighbouring columns

**Comment by MrXandbadas** [comment]
could it be fixed by putting in a min width and height in txColumn1.vue
line 34 or 36?
Still combing through

**Comment by MrXandbadas** [comment]
Also noting that the Transfer Card doesn't always keep its shape, sometimes you  get an extra wide card

**Comment by Cryptwo9879** [comment]
Im quite sure ive tried this, it seems to render the string inside the div and thats why it forces itself out of shape, the way the cards work they shouldn't be allowed to stretch outside the columns set up
